services:

  reverse-proxy:
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker --entryPoints.tcpep.address=:7788
    ports:
      - "80:80"
      - "7788:7788"
      - "18080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cloud-network

  cloud-node-1:
    extends:
      file: common.yaml
      service: cloud-node
    networks:
      cloud-network:
        ipv4_address: 10.5.0.11
    volumes:
      - ../../../data/cloud-node-1:/deployments/data:rw

  cloud-node-2:
    depends_on:
      - cloud-node-1
    extends:
      file: common.yaml
      service: cloud-node
    networks:
      cloud-network:
        ipv4_address: 10.5.0.12
    volumes:
      - ../../../data/cloud-node-2:/deployments/data:rw

  cloud-node-3:
    depends_on:
      - cloud-node-2
    extends:
      file: common.yaml
      service: cloud-node
    networks:
      cloud-network:
        ipv4_address: 10.5.0.13
    volumes:
      - ../../../data/cloud-node-3:/deployments/data

  cloud-node-4:
    depends_on:
      - cloud-node-1
    extends:
      file: common.yaml
      service: cloud-node
    networks:
      cloud-network:
        ipv4_address: 10.5.0.4
    volumes:
      - ../../../data/cloud-node-4:/deployments/data

  cloud-node-5:
    depends_on:
      - cloud-node-1
    extends:
      file: common.yaml
      service: cloud-node
    networks:
      cloud-network:
        ipv4_address: 10.5.0.5
    volumes:
      - ../../../data/cloud-node-5:/deployments/data

  cloud-node-6:
    depends_on:
      - cloud-node-2
    extends:
      file: common.yaml
      service: cloud-node
    networks:
      cloud-network:
        ipv4_address: 10.5.0.6
    volumes:
      - ../../../data/cloud-node-6:/deployments/data

networks:
  cloud-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1