services:
  reverse-proxy:
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker --entryPoints.tcpep.address=:5555
    ports:
      - "80:80"
      - "5555:5555"
      - "18080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"

  cloud-node:
    # A container that exposes an API to show its IP address
    image: cloud-node
    scale: 5
    labels:
      - "traefik.tcp.routers.cloud-node.rule=HostSNI(`*`) || HostSNI(`*`) && ClientIP(`0.0.0.0`)"
      - "traefik.tcp.routers.cloud-node.tls=false"
      - "traefik.tcp.services.cloud-node.loadbalancer.server.port=5555"
      - "traefik.tcp.routers.cloud-node.entrypoints=tcpep"
