services:

  reverse-proxy:
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker --entryPoints.tcpep.address=:7777
    ports:
      - "80:80"
      - "7777:7777"
      - "18080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cloud-network


  cloud-node-1:
    extends:
      file: common.yaml
      service: cloud-node
    networks:
      cloud-network:
        ipv4_address: 10.5.0.11

  cloud-node-2:
    extends:
      file: common.yaml
      service: cloud-node
    networks:
      cloud-network:
        ipv4_address: 10.5.0.12

  cloud-node-3:
    extends:
      file: common.yaml
      service: cloud-node
    networks:
      cloud-network:
        ipv4_address: 10.5.0.13

  cloud-node-others:
    extends:
      file: common.yaml
      service: cloud-node
    scale: 5
    networks:
      - cloud-network

networks:
  cloud-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1